### ISSUE TITLE
AgentImpl requires logger too soon

### ISSUE THREAD

**Issue by ivansenic** [inspectIT/inspectit-oce#85]
We must not have a logger as a static field, but loaded only when the logging initialization is done. Yes, this means we can not print anything before logging is initialized :(

```
10:07:55,117 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 9.0.2.Final (WildFly Core 1.0.2.Final) started in 5009ms - Started 628 of 800 services (221 services are lazy, passive or on-demand)
Exception in thread "Attach Listener" 10:08:11,252 ERROR [stderr] (Attach Listener) java.lang.reflect.InvocationTargetException
10:08:11,253 ERROR [stderr] (Attach Listener) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:08:11,253 ERROR [stderr] (Attach Listener) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:08:11,253 ERROR [stderr] (Attach Listener) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:08:11,253 ERROR [stderr] (Attach Listener) 	at java.lang.reflect.Method.invoke(Method.java:498)
10:08:11,253 ERROR [stderr] (Attach Listener) 	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
10:08:11,253 ERROR [stderr] (Attach Listener) 	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
10:08:11,254 ERROR [stderr] (Attach Listener) Caused by: javax.xml.parsers.FactoryConfigurationError: Provider __redirected.__SAXParserFactory not found
10:08:11,254 ERROR [stderr] (Attach Listener) 	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:200)
10:08:11,254 ERROR [stderr] (Attach Listener) 	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:152)
10:08:11,254 ERROR [stderr] (Attach Listener) 	at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:232)
10:08:11,254 ERROR [stderr] (Attach Listener) 	at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:127)
10:08:11,254 ERROR [stderr] (Attach Listener) 	at ch.qos.logback.core.joran.event.SaxEventRecorder.buildSaxParser(SaxEventRecorder.java:79)
10:08:11,254 ERROR [stderr] (Attach Listener) 	at ch.qos.logback.core.joran.event.SaxEventRecorder.recordEvents(SaxEventRecorder.java:57)
10:08:11,254 ERROR [stderr] (Attach Listener) 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:151)
10:08:11,255 ERROR [stderr] (Attach Listener) 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
10:08:11,255 ERROR [stderr] (Attach Listener) 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
10:08:11,255 ERROR [stderr] (Attach Listener) 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
10:08:11,255 ERROR [stderr] (Attach Listener) 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
10:08:11,255 ERROR [stderr] (Attach Listener) 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
10:08:11,255 ERROR [stderr] (Attach Listener) 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
10:08:11,255 ERROR [stderr] (Attach Listener) 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
10:08:11,256 ERROR [stderr] (Attach Listener) 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
10:08:11,256 ERROR [stderr] (Attach Listener) 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
10:08:11,256 ERROR [stderr] (Attach Listener) 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
10:08:11,256 ERROR [stderr] (Attach Listener) 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
10:08:11,256 ERROR [stderr] (Attach Listener) 	at rocks.inspectit.oce.core.AgentImpl.<clinit>(AgentImpl.java:26)
10:08:11,256 ERROR [stderr] (Attach Listener) 	at java.lang.Class.forName0(Native Method)
10:08:11,256 ERROR [stderr] (Attach Listener) 	at java.lang.Class.forName(Class.java:348)
10:08:11,256 ERROR [stderr] (Attach Listener) 	at rocks.inspectit.oce.bootstrap.AgentManager.startOrReplaceInspectitCore(AgentManager.java:30)
10:08:11,256 ERROR [stderr] (Attach Listener) 	at rocks.inspectit.oce.agent.AgentMain.premain(AgentMain.java:36)
10:08:11,256 ERROR [stderr] (Attach Listener) 	at rocks.inspectit.oce.agent.AgentMain.agentmain(AgentMain.java:30)
10:08:11,257 ERROR [stderr] (Attach Listener) 	... 6 more
10:08:11,257 ERROR [stderr] (Attach Listener) Caused by: java.lang.ClassNotFoundException: __redirected/__SAXParserFactory
10:08:11,257 ERROR [stderr] (Attach Listener) 	at java.lang.Class.forName0(Native Method)
10:08:11,257 ERROR [stderr] (Attach Listener) 	at java.lang.Class.forName(Class.java:348)
10:08:11,257 ERROR [stderr] (Attach Listener) 	at javax.xml.parsers.FactoryFinder.getProviderClass(FactoryFinder.java:124)
10:08:11,257 ERROR [stderr] (Attach Listener) 	at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:188)
10:08:11,257 ERROR [stderr] (Attach Listener) 	... 29 more
Agent failed to start!
```

**Comment by JonasKunz** [comment]
So as I understand it the root problem here is the fact that logback uses a SAXParser for parsing the xml config.
The SAXParser is obtained via the following method:
https://docs.oracle.com/javase/7/docs/api/javax/xml/parsers/SAXParserFactory.html#newInstance()

As stated there, Applications are free to choose which SAXParser implementation is used.
JBoss now uses its custom implementation "__redirected/__SAXParserFactory". This implementation is however not yet available on the classpath when starting via javaagent.

**Comment by JonasKunz** [comment]
I would suggest a simple solution:
In the AgentManager class we wait until we can call SAXParserFactory.newInstance with success. Only then afterwards we start initializing the agent. The waiting and the initalization then of course has to happen on a separate, daemon thread so that the application can start in the background and initialize the SAXParserFactory.
